In [210]:
import numpy as np
import pandas as pd
import sys

kuku = pd.read_csv('main_database.csv')
# print(kuku)
# In[6]:


num_rating_df = kuku.groupby('Hostel_Name').count()['Hostel_Rating_Simple'].reset_index()
num_rating_df.rename(columns={'Hostel_Rating_Simple':'num_ratings'},inplace=True)



# In[7]:


avg_rating_df = kuku.groupby('Hostel_Name').mean()['Hostel_Rating_Simple'].reset_index()
avg_rating_df.rename(columns={'Hostel_Rating_Simple':'avg_rating'},inplace=True)
avg_rating_df


# In[8]:


popular_df = kuku.merge(avg_rating_df,on='Hostel_Name')
yoyo=popular_df.merge(num_rating_df,on='Hostel_Name')
# print(yoyo)
#popular_df


# In[9]:


yoyo = yoyo[yoyo['num_ratings']>=2].sort_values('avg_rating',ascending=False).reset_index()

# In[10]:



# In[11]:


yoyo['tags'] = yoyo['Hostel_Rating'] + yoyo['Hostel_Location'] + yoyo['Gender']
# print(yoyo)

# In[12]:


yoyo['tags'].apply(lambda x:[i.replace(" ","")for i in x])
yoyo


# In[13]:


#yoyo['tags'].apply(lambda x:[i.replace(" ","")for i in x])


# In[14]:


#yoyo['tags'] = yoyo['tags'].apply(lambda x: "".join(x))


# In[15]:


yoyo['tags'] = yoyo['tags'].apply(lambda x:x.lower())

# In[16]:


yoyo


# In[17]:


from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')
    


# In[18]:


vector = cv.fit_transform(yoyo['tags']).toarray()
vector

# print(vector)
# In[19]:


cv.get_feature_names()


# In[20]:


from sklearn.metrics.pairwise import cosine_similarity


# In[21]:


similarity = cosine_similarity(vector)
# print(similarity)
# In[22]:
# print(yoyo)


index = sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])
# print(index)
# yoyo = sorted(yoyo)
# print(yoyo)
# In[23]:


def recommend(Hostel_Name):
    hostel_index = yoyo[yoyo['Hostel_Name'] == Hostel_Name].index[0]
#     print(hostel_index)
    distances = similarity[hostel_index]
    name = set()
    loc = list()
    fee = list()
    avg = list()
    
#     print(distances)
    hostel_list= sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])
    for i in hostel_list:
        if( yoyo.iloc[i[0]].Hostel_Name != Hostel_Name):
            name.add(yoyo.iloc[i[0]].Hostel_Name)
            loc.append(yoyo.iloc[i[0]].Hostel_Location)
            avg.append(yoyo.iloc[i[0]].avg_rating)
            fee.append(yoyo.iloc[i[0]].Yearly_Hostel_Fees)
    
    
    
#     li = set(li)
    name = list(name)
    loc = list(loc)
    avg = list(avg)
    fee = list(fee)
#     for i in range(0, 3):
        
        
#             print(yoyo.iloc[i[0]].Hostel_Location)
#         loc.append(yoyo.loc[str(j)].Hostel_Location)
#         avg.append(yoyo.loc[str(j)].avg_rating)
#         fee.append(yoyo.loc[str(j)].Yearly_Hostel_Fees)
    for i in range(0, 3):
        print(f'{name[i]},{loc[i]},{avg[i]},{fee[i]}')

# # print(yoyo["Hostel_Name"] == "Scholars Park ")
recommend('dharma hostel')

pearl residency,bidholi,4.0,175000
pride hostel,bidholi,3.909090909090909,178000
kk residency,bidholi,3.909090909090909,175000

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [120]:
yoyo

,index,Hostel_Name,Hostel_Location,Yearly_Hostel_Fees,Gender,Hostel_Rating_Simple,Hostel_Rating,avg_rating,num_ratings,tags
0,223,lavish living,kandoli,220000,girls,4,four,4.166667,6,fourkandoligirls
1,224,lavish living,kandoli,220000,girls,3,three,4.166667,6,threekandoligirls
2,225,lavish living,kandoli,220000,girls,5,five,4.166667,6,fivekandoligirls
3,226,lavish living,kandoli,220000,girls,5,five,4.166667,6,fivekandoligirls
4,221,lavish living,kandoli,220000,girls,5,five,4.166667,6,fivekandoligirls
...,...,...,...,...,...,...,...,...,...,...
232,122,dharma hostel,bidholi,15000,boys,2,two,2.857143,7,twobidholiboys
233,121,dharma hostel,bidholi,15000,boys,4,four,2.857143,7,fourbidholiboys
234,120,dharma hostel,bidholi,15000,boys,1,one,2.857143,7,onebidholiboys
235,119,dharma hostel,bidholi,15000,boys,3,three,2.857143,7,threebidholiboys
236,118,dharma hostel,bidholi,15000,boys,3,three,2.857143,7,threebidholiboys

In [121]:
loc

NameError: name 'loc' is not defined

In [131]:
Recommended('lavish living')

NameError: name 'process' is not defined